module.exports.authService = require('./auth.service');
module.exports.emailService = require('./email.service');
module.exports.tokenService = require('./token.service');
module.exports.userService = require('./user.service');
module.exports.cityService = require('./city.service');
module.exports.businessVnService = require ('./businesses.service')
module.exports.districtService = require('./district.service')
module.exports.wardService = require ('./ward.service')
module.exports.industryService = require('./industry.service')
module.exports.businessWardService = require ( './businessesWard.service')
